### ISSUE TITLE
Context menu  and "Esc" to exit

### ISSUE THREAD

**Issue by grssam** [victorporof/Tilt#1]
One suggestions , since it uses webgl on canvas . why is there not a context menu to save the image ? It would be very nice to have it , and also pressing Escape to hide Visualization

**Comment by victorporof** [comment]
Hey, thanks a lot for the suggestion! Exporting the visualization to other browsers is a planned feature, coming soon, and just saving a snapshot of the current canvas is a great idea.
Keyboard shortcuts for init/hide/close/other events also are planned.

**Comment by grssam** [comment]
Hmm, I know this is going to be big . But for starters I suggested these two
features to be the first to enter as they are not many lines of code and
useful also.

On Tue, Jun 28, 2011 at 3:29 PM, victorporof <
reply@reply.github.com>wrote:

> Hey, thanks a lot for the suggestion! Exporting the visualization to other
> browsers is a planned feature, coming soon, and just saving a snapshot of
> the current canvas is a great idea.
> Keyboard shortcuts for init/hide/close/other events also are planned.
> 
> ## 
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/victorporof/Tilt/issues/1#issuecomment-1453542

## 

Girish Sharma
3rd Year Student
Civil Engineering Department
IIT Kharagpur

**Comment by victorporof** [comment]
Ok then, I will move the context menu and keyboard shortcuts somewhere on top of the TODO list.
Thanks!
