### ISSUE TITLE
Editor's window should have controls to move up/down in the DOM tree

### ISSUE THREAD

**Issue by Drugoy** [victorporof/Tilt#10]
1. There should be a "Go Up" button.
2. Double-clicking (or somehow else) on the child element's tag in the editor should "zoom in" to that element in the editor + maybe even "zoom in" the canvas to center on that element too. Centering on the element might be hard to do, since we need to face it from the front side. [And in the far future this action might gain smooth animations]
   I don't want to file a new issue, so I'll ask/request it here:
3. Why do buttons "attributes/css/html" are up above? Shouldn't they be on the editor's window? Anyways they appear only if this window is shown.

**Comment by victorporof** [comment]
1. Agreed
2. I think this can be done without too much hassle, will implement it in the next release.
3. Yes, they probably should be closer to the editor. Will fix.

**Comment by victorporof** [comment]
This is implemented using the html breadcrumbs in the integrated version of Tilt (Firefox >= 11), as part of the Inspector.
