### ISSUE TITLE
Hotkeys

### ISSUE THREAD

**Issue by Drugoy** [victorporof/Tilt#11]
Since I have Stylish installed - the hotkey "CTRL+SHIFT+M" is occupied by it.
I know there is also a hotkey "CTRL+SHIFT+L" that opens Tilt, but I have to keep that hotkey in mind, as if I go to "Menu > Tools > Web developer > Tilt" - it shows me the CTRL+SHIFT+M hotkey.

As I'm not sure that it is an intentional duplication of used hotkes (M and L), or it is a bug/temporary solution - I am opening this issue to make things clear.
If this duplication is intentional, then a smart check like "Is CTRL+SHIFT+M hotkey occupied by another add-on? if yes - then show CTRL+SHIFT+L hotkey in the menu" would be nice, if possible.

**Comment by victorporof** [comment]
Currently both M and L are implemented, it's more of a temporary solution. Since I want to avoid hotkey wars, I'll make M be used by default and let the users change this in the (soon to be finished) options dialog.

**Comment by Drugoy** [comment]
That'd be the most peaceful solution. :)

**Comment by victorporof** [comment]
Implemented the Options window, which has an input for the preferred hotkey. Requires browser restart.

**Comment by Drugoy** [comment]
yeah, I already saw that, that's nice

**Comment by victorporof** [comment]
Glad to hear that.
