### ISSUE TITLE
.swf files

### ISSUE THREAD

**Issue by ghost** [victorporof/Tilt#13]
It would be good to see .swf animations not just the Youtube .avi formats.

**Comment by victorporof** [comment]
This is not possible, because the way Flash is implemented and its closed proprietary nature.

**Comment by ghost** [comment]
Everything is possible."

 2011/9/30 Victor Porof <
reply@reply.github.com>

**Comment by ghost** [comment]
html5 animation?

victorporof : This is not possible, because the way Flash is implemented and its closed proprietary nature.

It would be good to see .swf animations not just the Youtube .avi formats.
