### ISSUE TITLE
Do not draw text/images on background layers

### ISSUE THREAD

**Issue by Drugoy** [victorporof/Tilt#14]
<img src="http://img69.imageshack.us/img69/6849/multishades.png">

As you see on the screenshot above - all the text is visually duplicated as it gets drawn on every background layers.
I'm not sure if it's possible, but could you make it not get drawn there? By HTML structure it takes place in some SINGLE element and not in any of it's ancestors.

p.s.: the same happens not only with text, but with images too.

**Comment by victorporof** [comment]
This is merely a default alpha setting. You can modify it if you click the layer colors button (second block button under the navigation controls on the left) and slide the alpha to maximum for no transparency. I could make the default setting more opaque.

**Comment by Drugoy** [comment]
Well, yes, I'm talking about the default settings, as otherwise I'd need to change the alpha value manually every time.

**Comment by victorporof** [comment]
Agreed. Added fix + new version on AMO (awaiting review).

**Comment by Drugoy** [comment]
Tested it. Now it looks better. Thanks for the fast fix.
