### ISSUE TITLE
Bug: part of the content is not painted

### ISSUE THREAD

**Issue by Drugoy** [victorporof/Tilt#15]
I tried to inspect this <a href="http://pipes.yahoo.com/pipes/pipe.run?_id=6cc33ec11340418ec7c3cb5025327fff&_render=rss">page</a>.
When I scrolled down: since some part of the page - the text is not shown, so I can only see the structure of the page, but not it's contents.
It looks like <a href="http://img405.imageshack.us/img405/6093/whitebug.png">this</a>

**Comment by Drugoy** [comment]
The bug is 100% reproducible for me and the whitening starts from the same place.

**Comment by victorporof** [comment]
There is a limitation on the maximum texture size allowed by the WebGL context depending on the hardware and drivers (usually 8192px), therefore Tilt is forced to clamp. There is a way to work around this, but it's quite complicated and not currently on the agenda.

**Comment by victorporof** [comment]
There is bug 710565 filed for this: https://bugzilla.mozilla.org/show_bug.cgi?id=710565 with more information about the problem. Closing the issue here to avoid duplicates.
