### ISSUE TITLE
Blank child nodes ? 

### ISSUE THREAD

**Issue by grssam** [victorporof/Tilt#2]
see this image http://i52.tinypic.com/2hxxc9.jpg 
there are some blank 0 width child nodes being drawn randomly in the page.
Happens on almost every page.

**Comment by victorporof** [comment]
I'm sure they're not randomly there, might be some unused p's, newlines or line breaks in the webpage itself. I'm only drawing anything that has the width and height > 1, so it's impossible for those to have 0 width.
I see they're appearing only at the end of the text lines.
Could you give me a link so I can examine the html?

**Comment by grssam** [comment]
They come up on every page , even on this one

On Thu, Jun 30, 2011 at 1:18 AM, victorporof <
reply@reply.github.com>wrote:

> I'm sure they're not randomly there, might be some unused <p>'s, newlines
> or line breaks in the webpage itself. I'm only drawing anything that has the
> width or height > 1, so it's impossible for those to have 0 width.
> I see they're appearing only at the end of the text lines.
> Could you give me a link so I can examine the html?
> 
> ## 
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/victorporof/Tilt/issues/2#issuecomment-1469917

## 

Girish Sharma
3rd Year Student
Civil Engineering Department
IIT Kharagpur

**Comment by victorporof** [comment]
Ok, tried a quick fix: could you please test and see if this is still happening? (this issue does not seem to be a problem on my machine). Thank you.

**Comment by grssam** [comment]
Its fixed now
