### ISSUE TITLE
Html Editing panel creates confusion

### ISSUE THREAD

**Issue by grssam** [victorporof/Tilt#3]
The panel on lower right (which opens up when we click on the rendering) is editable , creating a sense that we can edit the html of the page . I don't know if that is the case because even if we can change the html of the page , the rendering is not updated . And if we can't change the html of the clicked node, then the panel should not be editable.
Also the panel should have a title or something giving information about the node type, not just the content of node

**Comment by victorporof** [comment]
Actually, editing the html of the webpage is a planned feature which will be available once https://bugzilla.mozilla.org/show_bug.cgi?id=653656 is finished.

Will add a titlebar with the node type right now.

**Comment by grssam** [comment]
Waiting for the bug will take quite a time , and by that your Gsoc will be
over I guess.
Is there dependence on that bug , something important ?

On Fri, Jul 15, 2011 at 10:45 PM, victorporof <
reply@reply.github.com>wrote:

> Actually, editing the html of the webpage is a planned feature which will
> be available once https://bugzilla.mozilla.org/show_bug.cgi?id=653656 is
> finished.
> 
> Will add a titlebar with the node type right now.
> 
> ## 
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/victorporof/Tilt/issues/3#issuecomment-1581310

## 

Girish Sharma
3rd Year Student
Civil Engineering Department
IIT Kharagpur

**Comment by victorporof** [comment]
Yes, Tilt is highly dependent on that bug (which was created specially for Tilt). It won't take long for the implementation to be finished (probably way before my GSoC finishes), and anyway, I will still be working on Tilt after GSoC.

**Comment by grssam** [comment]
Hmm , I guess that bug relates to making a draft and not actually fixing something in firefox :) So it won't take time.
Also just another suggestion : Users single click all the time , sometimes without any intention to get the node data, its just normal to single click on a 3D thing. Using a double click as the shortcut for node data panel popup would mean that the user will double click only when he actually wants to see that panel , and not just for the fun of clicking.
I hope you get the point.

**Comment by victorporof** [comment]
Also, you didn't see the dependencies: https://bugzilla.mozilla.org/show_bug.cgi?id=653657 and https://bugzilla.mozilla.org/show_bug.cgi?id=653658 (which is done). From what I talked to people there, it won't take more than a day to implement, the only thing to do now is decide on the specifications :)

Thanks for the double click suggestions. I got it.

**Comment by victorporof** [comment]
Now implemented double click for showing the html editor.

**Comment by victorporof** [comment]
Reopening this issue until the MOZ_window_region_texture is implemented in Tilt, now that the JavaScript implementation of the WebGL extension is finished.

**Comment by victorporof** [comment]
Finished implementing mesh & visualization refresh procedures, but to avoid redundancy with other developer tools, the html/css editing can be done with Firebug or Style Editor (or any other similar extension). The source code popup is now readonly.
