### ISSUE TITLE
Problems with FF7

### ISSUE THREAD

**Issue by ghost** [victorporof/Tilt#4]
I'm getting the following error message when I try to run Tilt:

```
Error: this.f is null
Source File: chrome://tilt/content/Tilt-content.js
Line: 96
```

My specs:
Windows 7(64bit)
Firefox 7.0a2
Tilt 0.1

**Comment by victorporof** [comment]
It may be possible that your hardware doesn't support WebGL. I'll make a few changes, and then get back to you. Thanks for testing!

**Comment by bgreco** [comment]
I also get an error message, although it is different:

> Error: uncaught exception: [Exception... "Component returned failure code: 0x8007000e (NS_ERROR_OUT_OF_MEMORY) [nsIDOMHTMLCanvasElement.getContext]"  nsresult: "0x8007000e (NS_ERROR_OUT_OF_MEMORY)"  location: "JS frame :: chrome://tilt/content/Tilt-extension.js :: <TOP_LEVEL> :: line 120"  data: no]

I can run other WebGL stuff just fine.

Win7 x64
Firefox 7.0a2 (2011-07-20)
Tilt 0.1

**Comment by victorporof** [comment]
Closing because obsolete version. If there are any problems with the latest (0.9.1), please file a new issue.
Thank you!
