### ISSUE TITLE
"stairs" or split lines instead of straight ones

### ISSUE THREAD

**Issue by Drugoy** [victorporof/Tilt#6]
Are you going to fix this?

**Comment by Drugoy** [comment]
Sometimes they even transform to dashed lines, instead of solid.

**Comment by grssam** [comment]
This is not the fault of this bug, Firefox does not supports anti aliasing in WebGL , thus this addon can't use the feature to smooth out crisps and stairs .

**Comment by victorporof** [comment]
There is work to fix this in Firefox. See the bug here: https://bugzilla.mozilla.org/show_bug.cgi?id=615976

**Comment by Drugoy** [comment]
Thank you for pointing at the bug, will track it.

**Comment by Drugoy** [comment]
This bug landed on Nightly this Friday and now it looks WAY WAY better!

**Comment by victorporof** [comment]
Yes, I saw that. Yay!
