### ISSUE TITLE
Not working with iframes

### ISSUE THREAD

**Issue by Drugoy** [victorporof/Tilt#7]
On the pages with iframes it shows plain surface for the whole iframe.
http://my.jetscreenshot.com/3439/20110721-82zx-98kb.jpg
Is it possible to fix?

**Comment by victorporof** [comment]
I will investigate. If this is the case, it will be fixed in the next release.

**Comment by victorporof** [comment]
Fixed.

**Comment by Drugoy** [comment]
Verified Fixed. ;)
