### ISSUE TITLE
Selected element should be highlighted in the DOM tree at left

### ISSUE THREAD

**Issue by Drugoy** [victorporof/Tilt#9]
And it shouldn't be just highlighted: the DOM tree should also get scrolled to that element, so it gets centered in the list.

**Comment by victorporof** [comment]
Yes, good idea. I also plan implementing a search above it (by tag, class, id, attribute, anything).

**Comment by robcee** [comment]
selector?

**Comment by victorporof** [comment]
There is no more DOM tree in the integrated version of Tilt (Firefox >= 11). Currently, the element is instead highlighted in the html breadcrumbs part of the Inspector.
